// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dac2014.json.model;

import com.dac2014.json.model.Imagen;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Imagen_Roo_Configurable {
    
    declare @type: Imagen: @Configurable;
    
}
